### ISSUE TITLE
Overlapping scroll animation

### ISSUE THREAD

**Issue by AkshayChordiya** [prashantsolanki3/Snap-RecyclerView-Utils#6]
Hey,

I tried showing animation to list items on scrolling but they are overlapping.

In `ViewHolder`

```
@Override
public void animateViewHolder(SnapViewHolder snapViewHolder, int position) {
     snapViewHolder.itemView.startAnimation(AnimationUtils.loadAnimation(getContext(), R.anim.up_from_bottom));
}
```

In `up_from_bottom.xml`

```
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android"
    android:shareInterpolator="@android:anim/decelerate_interpolator">
    <translate
        android:fromXDelta="0%" android:toXDelta="0%"
        android:fromYDelta="100%" android:toYDelta="0%"
        android:duration="400" />
</set>
```

**Comment by prashantsolanki3** [comment]
Hey @AkshayChordiya!
I was unable to find the cause of your problem.
Try using [`ItemAnimator`](http://developer.android.com/reference/android/support/v7/widget/RecyclerView.ItemAnimator.html) instead of `animateViewHolder`.
Please do let me know how it goes.

**Comment by AkshayChordiya** [comment]
I'll try using ItemAnimator and let you know.

Regards,
Akshay Chordiya
