### ISSUE TITLE
Constrain the data type to ArrayList

### ISSUE THREAD

**Issue by baoxiehao** [prashantsolanki3/Snap-RecyclerView-Utils#7]
```
public void set(@Nullable ArrayList<T> data) {
    this.clear();
    if(data != null) {
        this.mData.addAll(data);
    }

    this.handleEmptyLayoutVisibility();
}
```

Why constrains to ArrayList not List? I try the example and find the data type List can't be cast to ArrayList, which is so bad, cause I'll need to alter the data type to ArrayList manually to make it work, or just give up...

**Comment by prashantsolanki3** [comment]
Hey @baoxiehao !
I've already switched most of the ArrayList with List. All the future versions will support List only.
I would suggest you to use [the beta version](https://github.com/prashantsolanki3/Snap-RecyclerView-Utils/releases/tag/2.0.0-beta-1) for now. It will solve you problem.

**Comment by baoxiehao** [comment]
Nice work done quickly
